// The finish sound. Three custom soft chimes ship in the app bundle
// (generated by scripts/make-sounds.py); UNUserNotifications can only play
// files it finds in ~/Library/Sounds or the app bundle root, so the chosen
// wav is installed into ~/Library/Sounds as "amtrino-<name>.wav" first.

import AppKit
import UserNotifications

enum NotifySound: String, CaseIterable {
    case calm, bloom, wood, system, silent

    var label: String {
        switch self {
        case .calm: return "Soft chime"
        case .bloom: return "Bloom"
        case .wood: return "Low wood"
        case .system: return "System default"
        case .silent: return "Silent"
        }
    }

    /// True for the bundled wavs (everything but system/silent).
    var isCustom: Bool { self != .system && self != .silent }

    static var current: NotifySound {
        get { NotifySound(rawValue: Settings.notifySoundRaw) ?? .calm }
        set { Settings.notifySoundRaw = newValue.rawValue }
    }

    /// The bundled wav, resolved from the SPM resource bundle.
    var bundleURL: URL? {
        guard isCustom else { return nil }
        return Bundle.module.url(forResource: rawValue, withExtension: "wav",
                                 subdirectory: "Sounds")
    }

    private var bundleSize: Int {
        guard let u = bundleURL,
              let s = try? u.resourceValues(forKeys: [.fileSizeKey]).fileSize
        else { return 0 }
        return s
    }

    /// The byte count doubles as a content fingerprint: macOS caches
    /// notification sounds BY FILENAME (verified 2026-08-14 — a changed
    /// wav under the same name kept playing the old audio), so changed
    /// audio must arrive under a name the cache has never seen.
    private var installedName: String {
        "amtrino-\(rawValue)-\(bundleSize).wav"
    }

    private var installedURL: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Sounds/\(installedName)")
    }

    /// What the banner plays. nil = a silent banner.
    var unSound: UNNotificationSound? {
        switch self {
        case .system: return .default
        case .silent: return nil
        default:
            NotifySound.install()
            return UNNotificationSound(
                named: UNNotificationSoundName(installedName))
        }
    }

    /// Copy every bundled wav into ~/Library/Sounds under its
    /// fingerprinted name; sweep stale amtrino-* copies (old fingerprints
    /// and the pre-fingerprint names) so nothing cached stays reachable.
    static func install() {
        let fm = FileManager.default
        let dir = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Sounds")
        try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
        let wanted = Set(allCases.filter(\.isCustom).map(\.installedName))
        for f in (try? fm.contentsOfDirectory(atPath: dir.path)) ?? []
        where f.hasPrefix("amtrino-") && !wanted.contains(f) {
            try? fm.removeItem(at: dir.appendingPathComponent(f))
        }
        for s in allCases where s.isCustom {
            guard let src = s.bundleURL else {
                NSLog("%@", "amtrino: sound \(s.rawValue).wav missing from bundle")
                continue
            }
            let dst = s.installedURL
            guard !fm.fileExists(atPath: dst.path) else { continue }
            do {
                try fm.copyItem(at: src, to: dst)
            } catch {
                NSLog("%@", "amtrino: sound install failed: \(error)")
            }
        }
    }

    // NSSound deallocates mid-play unless retained
    private static var player: NSSound?

    /// Audible preview when picking a sound from the menu.
    func preview() {
        switch self {
        case .silent: return
        case .system: NSSound(named: "Glass")?.play()
        default:
            guard let url = bundleURL else { return }
            NotifySound.player?.stop()
            NotifySound.player = NSSound(contentsOf: url, byReference: true)
            NotifySound.player?.play()
        }
    }

    /// The no-banner-permission fallback: still make the finish audible.
    func playFallback() { preview() }
}
